### ISSUE TITLE
Undefined variable: info_message

### ISSUE THREAD

**Issue by EmSeta** [stuartduff/WooCommerce-Dynamic-Pricing-Table#8]
Hi! Thanks for a great plugin.

When activating it and checking the product page, I get this error:

Notice: Undefined variable: info_message in /plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php on line 406

What could that be about?

**Comment by teclanDesign** [comment]
Looks like the call to the wc_add_notice( $info_message, 'notice' ); on line 356 and 406 causes the error because in certain cases the switch clause beforehand hasn't been met so $info_message has not been set. Would setting it to '' initially work, or just cause a blank notice to be output? In which case I imagine some sort of isset check would work. This seems to remove the errors:

```
if(isset($info_message)){
    wc_add_notice( $info_message, 'notice' );
}
```

**Comment by stuartduff** [comment]
Updated the plugin with a fix for this.
